### ISSUE TITLE
Failed to run the server locally on MacOS and Ubuntu 

### ISSUE THREAD

**Issue by seuplus** [Upload/Up1#71]
Hi. I like Up1 very much but fail to run it locally on MacOS and Ubuntu. 

I follow the [`Quick start`](https://github.com/Upload/Up1#quick-start) to install it. But when I run it with: node `node server.js`, the following errors occur:

MacOS:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1290:19)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at serv (/Users/seuplus/Up1/server/server.js:185:17)
    at init (/Users/seuplus/Up1/server/server.js:200:5)
    at main (/Users/seuplus/Up1/server/server.js:217:3)
    at Object.<anonymous> (/Users/seuplus/Up1/server/server.js:220:1)
    at Module._compile (module.js:569:30)
```

Ubuntu 16.04 LTS:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at serv (/home/seuplus/Up1/server/server.js:185:17)
    at init (/home/seuplus/Up1/server/server.js:200:5)
    at main (/home/seuplus/Up1/server/server.js:217:3)
    at Object.<anonymous> (/Users/seuplus/Up1/server/server.js:220:1)
    at Module._compile (module.js:410:26)
```

**Comment by andre-d** [comment]
Does osx prevent you from binding a low port number as a regular user? Is
the port in use? It is failing to bind due to permissions.

**Comment by seuplus** [comment]
Great advice! Thank you Sir.

It really works when I change listen port from `80` to `8080` in `server.conf`.

<img width="745" alt="screen shot 2017-06-24 at 14 16 51" src="https://user-images.githubusercontent.com/26323968/27506310-34eacad2-58e8-11e7-8abb-da549744fea9.png">
